### PR TITLE
rpc: direct server-to-server tensor transfer for a layer split

### PR DESCRIPTION
**Pull request by danielhanchen**
## What this does

A layer split over several RPC devices used to move every hidden state through the host that runs
the scheduler. `ggml_backend_sched_compute_splits` has no direct path between two RPC buffers on
different endpoints (`ggml_backend_rpc_buffer_cpy_tensor` returns false as soon as the sockets
differ), so each stage boundary fell back to `ggml_backend_tensor_copy`: a `GET_TENSOR` into a
host allocation on the coordinator, then a `SET_TENSOR` back out. Two transfers, a synchronize,
and the hidden state of every boundary crossing the coordinator's memory.

With this change the coordinator still issues every control command, but for a boundary between
two remote servers it issues one command instead of two and the data goes straight from one
server to the other. P stages form a ring: the coordinator sends the embeddings to stage 1,
stage 1 sends its output to stage 2, and so on back to the device that holds the output layer.

## Protocol

Minor version 2 -> 3. Every existing command byte and struct is unchanged, so old clients and
servers interoperate for everything else, and the new commands are only used after the HELLO
version check reports minor >= 3 on **both** endpoints.

* `RPC_CMD_COPY_TENSOR_TO` is sent to the server that holds the **source** tensor. Payload is
  `| src rpc_tensor | dst rpc_tensor | size | endpoint_len | destination endpoint |`. The source
  server validates the source region exactly as `RPC_CMD_GET_TENSOR` does (`deserialize_tensor`
  plus the buffer range check), reads it, opens or reuses a connection to the destination
  endpoint using the same connect and HELLO negotiation a client uses (so RDMA when both rails
  allow it and TCP otherwise), and pushes the data as an ordinary `RPC_CMD_SET_TENSOR`. Nothing
  about the destination pointer is trusted on the source side: the destination applies its own
  `deserialize_tensor` and buffer range checks, the same ones it applies to a client.
* `RPC_CMD_PEER_BARRIER` is an empty request with a one byte response. A connection is served
  strictly in order, so its response proves the `SET_TENSOR` that preceded it has completed.
  The source server waits for it before answering the client, which is the ordering guarantee:
  the destination cannot compute before the write has landed, because the scheduler only sends
  `RPC_CMD_GRAPH_COMPUTE` to the destination after `RPC_CMD_COPY_TENSOR_TO` has returned.

Connections to other servers are cached per destination endpoint and closed when the client that
asked for them disconnects. Recoverable failures (destination unreachable, destination too old,
write rejected) come back as `result = 0` and the client falls back to the previous path; only a
malformed request or an out of bounds source closes the connection.

Serving several connections at once is what this needs, so a server now runs one thread per
connection over a shared buffer registry and a shared execution mutex; a session still owns and
frees only the buffers it allocated. The execution mutex is released before the peer connection
is used, so a ring of servers cannot deadlock on each other.

Client side, the RPC backend's `cpy_tensor_async` takes the RPC to RPC case when the two
endpoints differ. Two devices of one server keep the server-local `RPC_CMD_COPY_TENSOR`, and
every other combination returns false so the previous path runs unchanged. `GGML_RPC_P2P=0`
forces the old path for A/B.

## Commands and bytes per decode step

Client side counters (`GGML_RPC_STATS=1`), decode window, Qwen3.8-27B UD-Q4_K_XL, 32 rows,
three stages (`--device RPC0,RPC1,CUDA0 -sm layer --tensor-split 1,1,1`), so one RPC to RPC
boundary per step. The hidden state is 32 x 5120 x 4 B = 655360 B.

| per decode step | hub path | direct path |
|---|---|---|
| GET_TENSOR | 2.00 | 1.00 |
| SET_TENSOR | 12.00 | 11.00 |
| COPY_TENSOR_TO | - | 1.00 |
| total commands | 16.00 | 15.00 |
| request bytes from the coordinator | 1 382 840 | 727 488 |
| response bytes to the coordinator | ~1 310 720 | ~655 360 |

One `GET_TENSOR` plus one `SET_TENSOR` become one `COPY_TENSOR_TO` per boundary, and 1.31 MB per
step stops crossing the coordinator: 2.69 MB of RPC traffic per step becomes 1.38 MB, a 49
percent reduction. For P stages the saving is (P - 2) boundaries per step, so it grows with the
number of nodes while the coordinator's work stays flat.

CPU-only harness (`tests/cpu/rpc_p2p.sh`, three local rpc-servers on the CPU backend,
`--device RPC0,RPC1,RPC2 -sm layer`, the process host doing the embedding lookup), single stream,
exact per-step counts over the decode window:

| per decode step, 3 RPC devices | hub | direct |
|---|---|---|
| GET_TENSOR | 2.01 | 0.00 |
| SET_TENSOR | 18.99 | 17.01 |
| COPY_TENSOR_TO | - | 1.99 |
| SET_TENSOR bytes | 33 375 | 16 240 |

Two RPC to RPC boundaries, two `COPY_TENSOR_TO`, and the SET_TENSOR payload halves.

## Correctness

Greedy output over five prompts, 48 tokens, temperature 0, top_k 1, on the CPU-only harness:
md5 `177dc61e0703eba3bdaf7bf1131f0458` for all four arms - three stage and two stage,
`GGML_RPC_P2P=0` and `GGML_RPC_P2P=1` - which is the same md5 the existing RPC harnesses record.
`tools/server/tests`: 368 passed, 6 skipped, 199 deselected.

## Numbers on two GB10 nodes

Qwen3.8-27B UD-Q4_K_XL, 32 concurrent closed loop clients, npp 128 / ntg 256, 64 requests,
`-c 16384` (16386 for the three group cells), `--cache-ram 0`, `-fa on`, `-t 6`. Local CUDA0 holds
the last third and the output layer; two `ggml-rpc-server` processes on the peer (ports 50052 and
50053, one GPU between them) hold the first two thirds, `--tensor-split 1,1,1`.

| cell | arm | position in round | tok/s | TPOT ms | TTFT med s | util local | util peer | clocks.sm local / peer | tmax local / peer |
|---|---|---|---|---|---|---|---|---|---|
| h1_a | hub, N=1 | 1 | 101.52 | 292.0 | 6.55 | 34.1 | 58.5 | 2401 / 2445 | 55 / 69 |
| d1_a | direct, N=1 | 2 | 99.06 | 298.4 | 5.98 | 32.9 | 59.6 | 2398 / 1804 | 58 / 68 |
| h3_a | hub, 3 groups | 3 | 87.92 | 342.7 | 5.45 | 46.4 | 92.4 | 2396 / 2466 | 60 / 74 |
| d3_a | direct, 3 groups | 4 | 75.54 | 344.7 | 6.31 | 42.7 | 89.0 | 2392 / 1856 | 63 / 75 |
| d3_b | direct, 3 groups | 1 | 83.38 | 359.4 | 6.47 | 43.8 | 91.8 | 2393 / 1856 | 65 / 65 |
| h3_b | hub, 3 groups | 2 | 77.31 | 355.3 | 7.22 | 45.4 | 90.3 | 2392 / 1690 | 67 / 58 |
| d1_b | direct, N=1 | 3 | 96.98 | 302.4 | 6.33 | 31.3 | 60.2 | 2392 / 1690 | 63 / 56 |
| h1_b | hub, N=1 | 4 | 98.18 | 300.7 | 6.33 | 30.6 | 59.6 | 2392 / 1690 | 61 / 54 |

Two stage reference on the same binaries, `--device RPC0,CUDA0`, one rpc-server on the peer:

| cell | tok/s | TPOT ms | TTFT med s | util local | util peer | clocks.sm local / peer |
|---|---|---|---|---|---|---|
| N=1 | 101.13 | 293.8 | 5.34 | 46.1 | 47.6 | 2389 / 2438 |
| N=2 | 143.22 | 208.1 | 4.92 | 85.0 | 84.4 | 2400 / 2268 |

Reading these honestly: throughput does not move. The peer's mean SM clock falls monotonically
through each round (2466, 1856, 1690 MHz), so the first cell of a round is always the fastest one,
and the ranking of the two arms flips when the order is reversed: hub is ahead by 16 percent when
it runs first (round a) and behind by 8 percent when the direct arm runs first (round b). Both
arms are inside that band, so this pair and this topology do not separate them on tok/s. That is
expected here, because the two remote stages share one GPU on one node: the boundary the change
removes from the coordinator becomes a loopback transfer on the peer, and nothing is freed on the
one link that matters. What is unambiguous is the protocol accounting above, which is what scales:
for P stages on P nodes the change removes (P - 2) hidden state round trips per step from the
coordinator's link and memory, so the coordinator stops being a per-boundary relay and the wire
cost of a stage boundary no longer depends on where the scheduler runs.

Also visible in the table: three stages over the same two GPUs is worse than two stages
(143.2 tok/s at two stages with two groups against 77 to 88 at three stages with three groups),
so a third stage should only be added with a third node.

Known limitation, not fixed here: `RPC_CMD_COPY_TENSOR_TO` blocks the source server's connection
thread for the whole transfer plus the barrier, so with several pipeline groups over one
connection the groups serialise behind it. Moving the transfer to a per-destination worker and
letting the destination enforce the ordering with a sequence number, instead of the client
waiting for the acknowledgement, would remove that; it needs a second command on the destination
and another measurement window.

## Non-RPC workloads

Every line of this change is in `ggml/src/ggml-rpc/`:

```
 ggml/include/ggml-rpc.h         |   2 +-
 ggml/src/ggml-rpc/ggml-rpc.cpp  | 325 +++++++++++++++++++++++++++++++-----
 ggml/src/ggml-rpc/transport.cpp |   2 +-
```

`ggml-backend.cpp`, the scheduler, and the CUDA, Metal, Vulkan, CPU and HIP backends are not
touched, so a build with `-DGGML_RPC=OFF` contains none of it and `libggml-base` and `libllama`
gain no new behaviour when the RPC backend is not loaded. Checks on one GB10:

* `-DGGML_RPC=OFF -DGGML_CUDA=ON` configures and builds clean.
* `test-backend-ops -b CUDA0`: 13572/13572 tests passed, OK, on this branch and on the base, same
  count.
* Greedy generation on one GPU with no `--rpc`, three prompts, 64 tokens, temperature 0, top_k 1:
  md5 `1f99f8da109f7a456073901232e1f014` on this branch and on the base, byte identical.
* `llama-batched-bench` on one GPU with no `--rpc`, npp 512, ntg 128, npl 1 / 8 / 32, run as a
  base / new / base bracket in one window (whole run tok/s):

  | npl | base a | new | base b |
  |---|---|---|---|
  | 1 | 55.32 | 53.72 | 53.75 |
  | 8 | 232.26 | 212.29 | 211.87 |
  | 32 | 347.84 | 339.19 | 338.14 |

  The first run of the bracket is the fastest in every row (a cold GPU at the start of the
  window); the new binary matches the second base run to within 0.2 percent at npl 1 and 8 and
  sits between the two base runs at npl 32.

## Scope: this does nothing on a two node pair

Worth stating plainly, because the byte table above is easy to read as a decode win and it is not one here. The saving is (P - 2) boundaries per step. On the two DGX Spark pair P = 2, so there is no RPC to RPC boundary at all and this change is inert: the one crossing goes to the device holding the output layer, which is the coordinator's own CUDA0. The three stage cells above were run with two rpc-servers sharing one GPU on the peer precisely because that is the only way to make a P = 3 boundary exist on two machines, and they show three stages over two GPUs is worse than two stages regardless of the arm.

There is also now a measurement that bounds what any interconnect change on the pair can be worth. A two node layer split moves 6.84 MB per decode step in total, which is 0.34 ms of a 220 ms step against the measured 20.31 GB/s NCCL bus bandwidth, under 0.005x of end to end speedup. Removing 1.31 MB of that would be worth under 0.001x even if the boundary existed. So this PR should be read as a three or more node capacity and scaling change, plus the per connection threaded rpc-server it introduces, and not as a throughput change for the pair. The honest reading of the tok/s table stands as written: the arms do not separate.

### CODE REVIEW

**Comment by danielhanchen** [comment]
@codex review

**Comment by danielhanchen** [comment]
@codex security review

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 1]
```diff
@@ -1008,6 +1036,67 @@ static bool rpc_supports_batched_get(const socket_ptr & sock) {
...
+    }
+
+    auto src_sock = get_socket(src_ctx->endpoint);
+    auto dst_sock = get_socket(dst_ctx->endpoint);
+    if (!rpc_supports_p2p(src_sock) || !rpc_supports_p2p(dst_sock)) {
+        return false;
+    }
+
+    // anything queued for the destination has to be on the wire before the peer write lands
+    rpc_flush_deferred_guarded(dst_sock);
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Fixed in 4bc3b0a9b. You are right that flushing orders the bytes and nothing else, and that the two connections are separated only by the destination execution mutex.

RPC_CMD_PEER_BARRIER already carries exactly the meaning needed, that everything received earlier on a connection has been served, so it is issued on dst_sock before the copy starts and a failure there falls back to routing through the client. Worth noting that this adds one round trip per cross-stage copy; it is a small message on the rail, but I would rather measure that cost on hardware than assume it is free, so I am treating it as open until it is measured.

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 2]
```diff
@@ -1885,6 +2028,111 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
...
+    rpc_msg_copy_tensor_to_hdr hdr;
+    memcpy(&hdr, input.data(), sizeof(hdr));
+    if (input.size() != sizeof(hdr) + (size_t) hdr.endpoint_len) {
+        return false;
+    }
+    const std::string endpoint((const char *) input.data() + sizeof(hdr), hdr.endpoint_len);
+
+    const size_t msg_size = sizeof(rpc_tensor) + sizeof(uint64_t) + (size_t) hdr.size;
+    if (p2p_buf.size() < msg_size) {
+        p2p_buf.resize(msg_size);
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Fixed in e2e3c040d. Both failure modes confirmed: a large hdr.size aborts on an uncaught bad_alloc, and a value near SIZE_MAX wraps msg_size so the two header copies run past the end of the vector.

The checks already existed further down the function, so the fix is ordering rather than new validation: the sizing and the header copies now happen after the buffer and tensor bounds checks, where hdr.size is known to fit.

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 3]
```diff
@@ -1885,6 +2028,111 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
...
 }
 
+socket_ptr rpc_server::get_peer_socket(const std::string & endpoint) {
+    auto it = peer_socks.find(endpoint);
+    if (it != peer_socks.end()) {
+        return it->second;
+    }
+    // the same connect and HELLO negotiation a client does, so a server to server link uses
+    // RDMA whenever both rails allow it and TCP otherwise
+    auto sock = get_socket(endpoint);
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Fixed in 8b1cbcd87. This one contradicted the function comment directly, which promises that an unreachable or too old destination comes back as result = 0.

negotiate_hello and get_socket take may_fail now, set only for peer connections opened from inside a server, and return failure instead of hitting RPC_STATUS_ASSERT. Client behaviour is unchanged.

**Comment by danielhanchen** [comment]
@codex review

**Comment by danielhanchen** [comment]
@codex review

File: ggml/include/ggml-rpc.h [hunk 4]
```diff
@@ -7,7 +7,7 @@ extern "C" {
 #endif
 
 #define RPC_PROTO_MAJOR_VERSION    5
-#define RPC_PROTO_MINOR_VERSION    2
+#define RPC_PROTO_MINOR_VERSION    3
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/include/ggml-rpc.h]: Confirmed and accepted. ggml-rpc.h has RPC_PROTO_MINOR_VERSION at 3 on this branch, hello() advertises it unconditionally, and the client check at ggml-rpc.cpp:520 rejects any server whose minor exceeds its own. So a deployed 5.2 client cannot open a connection to a 5.3 server at all, for any command, which is a hard break from a change that is otherwise purely additive.

Worth being precise about why this cannot be fixed on the client side: the 5.2 client already exists, so nothing we change in the client helps the case you describe. The server has to stay acceptable to it.

The mechanism for that is already present and I had not used it. conn_caps appears in both rpc_msg_hello_req and rpc_msg_hello_rsp, so capability negotiation is already bidirectional and fixed size, and it is what this branch uses for transport negotiation. Peer to peer support belongs there rather than in the version number: keep the advertised minor at 2, add a caps bit for the peer copy, and replace the server_minor >= 3 gate in get_peer_socket and rpc_supports_p2p with a caps check. A 5.2 client then connects as before and simply never sees the bit, and a new client discovers the feature without a version bump that locks old clients out.

Not fixed yet, so no thumbs-up from me. Flagging one consequence for whoever lands it: the minor bump cannot simply be reverted in isolation, because the gate currently keys on it, so the caps bit and the gate change have to go in together or peer copies will be attempted against servers that do not support them.

[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/include/ggml-rpc.h]: Fixed in 08ad5b62a, though not the way I said I would in my previous reply, and the difference is worth recording because my first answer would not have worked.

I said to put the bit in conn_caps. That is wrong. update_caps treats *any* non-zero byte in the caps blob as "this peer speaks RDMA", and rdma_caps (qpn 4 + psn 4 + gid 16) already fills all 24 bytes exactly. So there is no spare bit, and had there been one, setting it on an RDMA-less peer would have made the other side believe RDMA was available and try to activate it. I should have read update_caps before recommending it.

What works is the byte next to it: rpc_msg_hello_rsp carries major, minor, patch and one explicit padding byte. It is fixed size, already on the wire, and every existing client reads it as padding and ignores it. The minor is back to 2 and peer copy support is advertised as a flag in that byte, so a 5.2 client connects exactly as before and never sees the flag, and an old server sends zero and is never asked for a peer copy. Both gates that keyed on minor >= 3 now test the flag.

This also removes the coupling I warned about, since the version bump and the gate are no longer tied together.

**Comment by danielhanchen** [comment]
@codex review

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 5]
```diff
@@ -1885,6 +2061,119 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
...
 
+socket_ptr rpc_server::get_peer_socket(const std::string & endpoint) {
+    auto it = peer_socks.find(endpoint);
+    if (it != peer_socks.end()) {
+        return it->second;
+    }
+    // the same connect and HELLO negotiation a client does, so a server to server link uses
+    // RDMA whenever both rails allow it and TCP otherwise
+    // may_fail: a destination that is down or restarting is a recoverable condition here
+    auto sock = get_socket(endpoint, /* may_fail */ true);
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Confirmed and fixed in 0008f4691.

`socket_t::connect()` leaks on three paths, not just the `::connect()` one: `set_no_delay()`, `gethostbyname()` returning NULL, and `::connect()` itself all return `nullptr` after `socket()` succeeded, with the descriptor still raw. Your severity argument is the part that makes it worth fixing rather than noting: before peer copies this cost at most one descriptor per process, because a client that cannot connect aborts. `get_peer_socket()` reaches the same code once per tensor per boundary crossing, does not cache failed peers, and treats a refused connection as recoverable, so the leak becomes unbounded and ends with the server unable to connect to peers or accept clients.

RAII already existed and was simply not being used: `socket_t::impl`'s destructor calls `closesocket()`. So the fix is to adopt the descriptor into the `socket_ptr` immediately and let the early returns close it, rather than adding a close to each path.

`accept()` and `create_server()` have the same shape and are fixed the same way. `accept()`'s matters most of the three after `connect()`, since it is reached once per client connection rather than once per process.

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 6]
```diff
@@ -1885,6 +2061,119 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
...
+    }
+
+    socket_ptr peer = get_peer_socket(endpoint);
+    if (peer == nullptr) {
+        return true;
+    }
+
+    LOG_DBG("[%s] %" PRIu64 " bytes to %s\n", __func__, hdr.size, endpoint.c_str());
+
+    if (!send_rpc_cmd(peer, RPC_CMD_SET_TENSOR, p2p_buf.data(), msg_size)) {
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Confirmed and fixed in 0008f4691.

Verified both halves of this: `send()` is called with a flags argument of `0` in `socket_t::impl::send_data()`, and there is no `MSG_NOSIGNAL`, `SO_NOSIGPIPE` or `SIGPIPE` handling anywhere under `ggml/src/ggml-rpc/` or `tools/rpc/`. So on POSIX the default action applies and the process dies. This was survivable while every send belonged to a client that aborts on a broken connection anyway; it is not survivable for a source server writing to a cached peer connection, where a restarted destination is precisely the case that is supposed to end in `result = 0`. Instead it killed the source server and every client it was serving.

Fixed portably rather than with `MSG_NOSIGNAL` alone, since that is not available everywhere:

- where `MSG_NOSIGNAL` exists (Linux, most BSDs) sends pass it,
- Apple has no `MSG_NOSIGNAL`, so descriptors get `SO_NOSIGPIPE` set once at creation instead, in `connect()`, `accept()` and `create_server()`,
- Windows has no `SIGPIPE` and is unaffected either way.

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 7]
```diff
@@ -1584,7 +1748,7 @@ ggml_tensor * rpc_server::deserialize_tensor(struct ggml_context * ctx, const rp
         result->nb[i] = tensor->nb[i];
     }
     result->buffer = reinterpret_cast<ggml_backend_buffer_t>(tensor->buffer);
-    if (result->buffer && buffers.find(result->buffer) == buffers.end()) {
+    if (result->buffer && shared.buffers.find(result->buffer) == shared.buffers.end()) {
```
[the remark this answers is not in the document]
Comment (danielhanchen) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Confirmed and fixed in de47be8ba.

Verified the regression is exactly as described. `deserialize_tensor()` validated `result->buffer` against `shared.buffers`, which the struct comment itself describes as "every live buffer of this process", so any connection could name another session's buffer and reach it through `GET_TENSOR`, `SET_TENSOR` or a graph node via `create_node()`. `buffer_get_base()` and `buffer_clear()` had the same problem: they were checking process-wide liveness where they meant ownership. `free_buffer()` was the only command already checking `owned_buffers`.

`deserialize_tensor()` now validates against `owned_buffers` and takes an `allow_foreign` flag. Exactly one caller sets it, which is your "narrowly authorized" point: `SET_TENSOR`. The destination of a peer copy receives that command on the connection the source server opened, not on the connection of the client that allocated the buffer, so it is the one path that genuinely has to resolve a buffer another session owns. The write remains bounded by the existing buffer range checks. `GET_TENSOR`, `GRAPH_COMPUTE`, `memset_tensor` and the local copy path are back to being confined to the session.

`owned_buffers` is maintained on allocation, on `free_buffer()`, and in `~rpc_server()`, so it carries the same lifetime the per-connection registry had before the move.

Two things I want to state plainly rather than overclaim. First, this restores the pre-peer-copy isolation property for every command except the peer write itself; it is not authentication. The RPC server has none, and a caller that can open a connection can still address the destination buffer of a peer copy through `SET_TENSOR`. Closing that too requires the destination to be told in advance which writes to expect, which is a protocol change and out of scope here. Second, I considered marking peer connections at `HELLO` and gating on that instead, and rejected it: `rpc_msg_hello_req` is a fixed-size struct read as such by the server, so growing it locks out existing clients, which is the same compatibility trap that made me revert the protocol minor bump on this PR. A self-declared flag would also not be a real control, since any client could set it.

The build is clean. The live peer-copy regression test on the two-node pair has not run yet; the GPU reservation for it is queued behind other work and I will report the result here when it lands rather than assume it.

**Comment by danielhanchen** [comment]
@codex review

**Comment by danielhanchen** [comment]
Merged the base branch in to clear the conflict (999cdbcb4). This was not a mechanical merge, so recording what changed and why.

`feature/rpc-stage2` had moved nine commits since this branch forked: the async-copy event pool recycling, the source-side async copy interface entry, the backend API version bump, GET_TENSORS entry validation, batched get advertised as a server flag, the staging-event wait fix, and two server-side commits. Two conflicts, both from the branches independently growing the same thing.

**The one worth reviewing: `srv_flags` bit 0 was claimed twice.** Batched get and peer copy were developed on separate branches and each assigned itself `1 << 0`. Taking either side of that conflict, or keeping both enumerators at bit 0, compiles cleanly and ships a wire-level collision. A server built with batched get but without peer copy sets bit 0; a client that knows about peer copy reads that same bit as peer-copy support and sends it `RPC_CMD_COPY_TENSOR_TO`, a command it does not implement. That is a cross-version failure between two builds that each look correct on their own, and nothing in the type system objects to it.

The features now occupy distinct bits. Batched get keeps bit 0, because that value is already published on this branch and anything already built against it would otherwise be wrong; peer copy moves to bit 1. `hello()` advertises both, since this server implements both.

**The second: `rpc_conn_state::server_flags` was added on both branches.** Git auto-merged `transport.h` without reporting a conflict and produced a struct with the field declared twice. That does not compile, so it was caught immediately, but it is worth noting that the clean auto-merge was wrong.

Checked rather than assumed, on CPU with no GPU involved: the merged `ggml-rpc-server` advertises `flags: 0x03` on the wire, and a `llama-server` generating against it over a real RPC socket completes normally. Both client-side gates survived the merge and each remains keyed to its own flag, so `GGML_RPC_NO_BATCHED_GET` and the peer-copy gate still work independently.

The head moved, so this needs another look.

**Comment by danielhanchen** [comment]
@codex review

**Comment by danielhanchen** [comment]
@codex review

**Comment by danielhanchen** [comment]
## Defect report, not a review of this PR

Issues are disabled on this repository, so this is filed here because this PR is where it was
reproduced most recently and most repeatedly. It is **not** caused by this PR and it is not fixed
by it; it needs an owner of its own.

---

## What happens

At 32 concurrent streaming clients against `llama-server`, exactly **one request of every 64
returns no tokens**. The client sees a completed HTTP response with no content; the server logs no
error. It is one request per cell, reproducibly, not a rate.

## Where it has been seen

It is not a property of any one branch, which is why this is an issue rather than a comment on a
pull request:

* PR #196, three stage split (`--device RPC0,RPC1,CUDA0 -sm layer --tensor-split 1,1,1`,
  Qwen3.8-27B UD-Q4_K_XL, `-c 16386 --parallel 32 --cache-ram 0 -fa on -t 6`), 32 concurrent
  closed loop clients, npp 128 / ntg 256, 64 requests per cell: **all five cells** reported
  `n_err 1`, in the hub arm (`GGML_RPC_P2P=0`) and in the direct arm (`GGML_RPC_P2P=1`) alike, so
  it is unaffected by the feature that branch adds.
* PR #187's own description records the same thing independently: "Every 32-user cell in every arm,
  including the two without speculation, had one request of 64 return no tokens; it is present in
  the arms this PR does not touch".

Two unrelated branches, two harnesses, the same one-in-sixty-four. Nobody has picked it up.

## Reproduction

Any 27B layer split over two nodes, or any server configuration that sustains 32 concurrent
streaming completions, with a closed loop client that counts tokens per request:

```
llama-server -m Qwen3.8-27B-UD-Q4_K_XL.gguf -ngl 99 -fa on -c 16386 --parallel 32 \
    --cache-ram 0 -t 6 --metrics ...
# 32 concurrent clients, 2 requests each, npp 128, ntg 256, stream=true, ignore_eos
```

One of the 64 requests ends with zero streamed content chunks. The server's
`llamacpp:tokens_predicted_total` accounts for the tokens of the other 63 only, so the loss is
upstream of the counter rather than a client-side parse failure.

## Why it matters

A serving deployment at this concurrency silently drops 1.6 percent of requests with a 200 and an
empty body. Nothing in the log marks it, so it is invisible without a client that checks token
counts per request, and every throughput figure taken at 32 rows is quoted over 63 requests while
being divided by the wall time of 64.

## What is not yet known

Whether it is the slot handover, the streaming path, or the HTTP layer. PR #187 also records a
different but possibly related failure at 256 concurrent streams, where responses are truncated
mid-stream with no server-side error, which suggests the HTTP or streaming path rather than
sampling.
